---
- name: Deploy Web Page to Apache on ECS Instance
  hosts: localhost
  become: yes  # Enables sudo for tasks without prompting for a password

  tasks:
    - name: Ensure Apache HTTP Server is Installed
      yum:
        name: httpd
        state: present

    - name: Start and Enable Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Copy Web Files to Apache Document Root
      copy:
        src: "{{ playbook_dir }}/"
        dest: /var/www/html/
        owner: apache
        group: apache
        mode: '0644'

    - name: Restart Apache
      service:
        name: httpd
        state: restarted
